[project]
name = "astral"
version = "0.1.0"
description = "An asteriod style game made in python with game development ideas tested"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]
